### ISSUE TITLE
deploy on geth in dev mode

### ISSUE THREAD

**Issue by mazeboard** [SmarDex-Dev/smart-contracts#9]
I would like to deploy smardex locally on a running geth in dev mode

$ geth --dev --http --http.api eth,web3,debug,personal,net

in another console
$ npx hardhat deploy  --network localhost --reset
Nothing to compile
No need to generate any newer typings.
deployment address: 0x42Ab9c9E8BDBB7bACA96C8ea6aa252e72D8004D2
An unexpected error occurred:

Error: ERROR processing /home/taoufik/workspace/SmarDex-Dev/smart-contracts/deploy/001_smardex_factory.ts:
Error: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"name":"ProviderError","_stack":"ProviderError: insufficient funds for transfer\n    at HttpProvider.request (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async EthersProviderWrapper.send (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)","code":-32000,"_isProviderError":true}, method="estimateGas", transaction={"from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0xd09dc300"},"to":"0x42Ab9c9E8BDBB7bACA96C8ea6aa252e72D8004D2","value":{"type":"BigNumber","hex":"0x0de0b6b3a7640000"},"type":2,"accessList":null}, code=INSUFFICIENT_FUNDS, version=providers/5.7.2)
    at Logger.makeError (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at checkError (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:98:16)
    at EthersProviderWrapper.<anonymous> (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:642:20)
    at step (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at DeploymentsManager.executeDeployScripts (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1223:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DeploymentsManager.runDeploy (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)
    at async SimpleTaskDefinition.action (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/hardhat-deploy/src/index.ts:422:5)
    at async Environment._runTaskDefinition (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at async Environment.run (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
    at async SimpleTaskDefinition.action (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/hardhat-deploy/src/index.ts:568:32)
    at async Environment._runTaskDefinition (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:14)
    at async Environment.run (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:14)
    at async SimpleTaskDefinition.action (/home/taoufik/workspace/SmarDex-Dev/smart-contracts/node_modules/hardhat-deploy/src/index.ts:653:5)

I highly appreciate a step-by-step guide on how to do that

do I need to create a new contract in geth and use it instead of from = 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266

I would like to run tests locally using geth node running in dev mode

Kind regards

**Comment by mazeboard** [comment]
there is no clear and complete documentation to deploy smardex, I am getting gas limit error when I start a hardhat node

please give me details on how to deploy smardex (ie. local geth node)
